# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20161030_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessAuthority',
            fields=[
                ('ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phoneNo', models.CharField(max_length=12)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Hostel')),
            ],
        ),
    ]
