# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_messauthority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caterer',
            name='password',
        ),
        migrations.AlterField(
            model_name='tempopt',
            name='hostel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Hostel'),
        ),
    ]
