# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20161101_0355'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tempopt',
            unique_together=set([('student', 'hostel', 'startDate', 'startMealType')]),
        ),
    ]
