# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20161101_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='messaccounts',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
