# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_messaccounts_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rated',
            old_name='sanity',
            new_name='sanitary',
        ),
    ]
