# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20161103_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rated',
            old_name='sanitary',
            new_name='cleanliness',
        ),
    ]
