# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20161103_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belongsto',
            name='endDate',
            field=models.DateField(null=True),
        ),
    ]
