# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_auto_20161121_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='hostel',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
