# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_auto_20161121_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewed',
            name='review',
            field=models.CharField(max_length=1000),
        ),
    ]
