# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_auto_20161121_1632'),
        ('mainApp', '0009_auto_20161121_1114'),
    ]

    operations = [
    ]
