# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_announcement'),
        ('mainApp', '0010_auto_20161121_1632'),
    ]

    operations = [
    ]
