# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_merge_20161121_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='subject',
            field=models.CharField(default='Notification', max_length=50),
        ),
    ]
