# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_announcement_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wastage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('wasted', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Hostel')),
            ],
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='wasted',
        ),
        migrations.AlterUniqueTogether(
            name='wastage',
            unique_together=set([('hostel', 'day')]),
        ),
    ]
