# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_auto_20161122_0029'),
        ('mainApp', '0011_merge_20161121_2029'),
    ]

    operations = [
    ]
