# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_merge_20161122_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timecost',
            old_name='originalCost',
            new_name='cost',
        ),
        migrations.AddField(
            model_name='timecost',
            name='mealType',
            field=models.CharField(default='breakfast', max_length=20),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='timecost',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='timecost',
            name='startTime',
        ),
        migrations.RemoveField(
            model_name='timecost',
            name='subsidisedCost',
        ),
        migrations.AlterUniqueTogether(
            name='timecost',
            unique_together=set([('hostel', 'mealType')]),
        ),
    ]
