# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_auto_20161122_1757'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeCost',
            new_name='Cost',
        ),
    ]
